quarkus:
  http:
    port: 8081
  smallrye-openapi:
    path: "/openapi"
#    info-title: "Person Service"
#    info-contact-email: "mvandepe+person_service_support@redhat.com"
#    info-contact-name: "Person service support"
  swagger-ui:
    always-include: true
    path: "/openapi-ui"
#"%dev":
#  quarkus:
#    smallrye-openapi:
#    info-title: "Example API (development)"
#"%test":
#  quarkus:
#    smallrye-openapi:
#    info-title: "Example API (test)"