apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: <NAMESPACE>
  name: 'person-service-app'
  annotations: {}
spec:
  selector:
    matchLabels:
      app: person-service
  replicas: 1
  template:
    metadata:
      labels:
        app: person-service
    spec:
      containers:
        - name: container
          image: >-
            quay.io/appdev_playground/:person-service:<VERSION>
          ports:
            - containerPort: 8081
              protocol: TCP
          env: []
      imagePullSecrets: []
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  paused: false
